Update GHA to allow manually supplying tag, and always using tag.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,6 +5,9 @@ on:
     types: [published]
   workflow_dispatch:
     inputs:
+      tag:
+        description: "Tag to release (e.g. v0.0.1)"
+        required: true
       skip_publish:
         description: "Skip binary publish"
         required: false
@@ -15,6 +18,10 @@ on:
         default: "false"
       skip_homebrew:
         description: "Skip homebrew publish"
+        required: false
+        default: "false"
+      skip_validate:
+        description: "Skip GoReleaser validation"
         required: false
         default: "false"
 
@@ -29,6 +36,17 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           fetch-depth: 0
+
+      - name: Checkout release tag
+        run: |
+          git fetch --tags
+          TAG="${{ github.event.release.tag_name || github.event.inputs.tag }}"
+          if [ -z "$TAG" ]; then
+            echo "Error: No tag provided in release event or workflow_dispatch input"
+            exit 1
+          fi
+          echo "Checking out tag $TAG"
+          git checkout -- "refs/tags/$TAG"
 
       - name: Set up Go (from go.mod)
         uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
@@ -56,6 +74,7 @@ jobs:
           args: >
             release --clean
             ${{ github.event.inputs.skip_publish == 'true' && ' --skip publish' || '' }}
+            ${{ github.event.inputs.skip_validate == 'true' && ' --skip validate' || '' }}
             ${{ github.event.inputs.skip_docker == 'true' && ' --skip docker' || '' }}
             ${{ github.event.inputs.skip_homebrew == 'true' && ' --skip homebrew' || '' }}
         env:
